name: Generate Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */5 * *'

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Release
        run: |
          latest_release=$(gh release list | head -n 1 | grep -oP 'v\d+\.\d+\.\d+' | head -n 1)

          major=$(echo $latest_release | cut -d. -f1 | sed 's/v//')
          minor=$(echo $latest_release | cut -d. -f2 | sed 's/v//')
          patch=$(echo $latest_release | cut -d. -f3 | sed 's/v//')

          if [ $minor -eq 5 ]; then
              minor=0
              major=$((major + 1))
          else
              minor=$((minor + 5))
          fi

          new_tag="v$major.$minor.$patch"

          release_date=$(date +%d-%m-%Y)

          release_notes="Release $new_tag - $release_date"

          gh release create $new_tag --title "Release $new_tag" --notes "$release_notes"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}